name: Python Package using Conda

on: 
  issue_comment:
    types: [created,edited,deleted]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: qq bot
      run: |
        curl --location --request POST 'http://mc.mesord.com:8098/api/send_msg_auto' --header Content-Type: 'application/json' --data-raw '{"token":"${{ secrets.KEY }}","uid":913468406,"msg":"test"}'
